package com.example.tryggaklassenpod.screens

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Card
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.tryggaklassenpod.dataClasses.Comments

// if user adds a comment
//import android.widget.Toast

@Composable
fun CommentsSection(comments: List<Comments>) {
    val nrOfComments = comments.size
    Column(){
        Text(
            text = if (nrOfComments == 1) "$nrOfComments Comment" else "$nrOfComments Comments",
            style = MaterialTheme.typography.headlineSmall,
        )
        // 1. add a button to reveal all the comments (show / hide comments button)
        // 2. At the bottom of the list add field to write a new comment
        // 3. autogenerated names
        // 4. when submitted, toast the user!!
    }

    Column {
        for (comment in comments) {
            Card(
                modifier = Modifier
                    .padding(5.dp)
                    .height(250.dp)
                    .fillMaxSize()
            ) {
                comment.author?.let {
                    Text(
                        text = it,
                        fontSize = 20.sp
                    )
                }
                comment.comment?.let {
                    Text(text = it)
                }
            }
        }
    }
}
//
//
////@Preview(showSystemUi = true, showBackground = true)
////@Composable
////fun CommentsSectionPreview() {
////    CommentsSection(episodesList[0].comments)
////}